### ISSUE TITLE
Map not working after update from 1.0.12 to 1.0.13

### ISSUE THREAD

**Issue by MarcelRiedeman** [Gugustinette/Nuxt-Leaflet#22]
Hi everyone,

After updating nuxt3-leaflet from version 1.0.12 to 1.0.13, my map is no longer showing. I attempted to solve the issue by installing vue-leaflet, but it did not resolve the problem.

Here’s the relevant HTML code:
```html
<template>
  <div class="h-full w-full">
    <LMap
        ref="map"
        :zoom="default_location.zoom"
        :minZoom="3"
        :center="default_location.coordinates"
    >
      <LTileLayer
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          attribution="&amp;copy; <a href=&quot;https://www.openstreetmap.org/&quot;>OpenStreetMap</a> contributors"
          layer-type="base"
          name="OpenStreetMap"
      />
    </LMap>
  </div>
</template>
```

Additional Information:
Nuxt Version: issue on both Nuxt3.10 and Nuxt3.12

Package list:
```sh
>>> pnpm list
Legend: production dependency, optional only, dev only

nuxt-app ... (PRIVATE)

dependencies:
@nuxt/ui 2.13.0
@nuxtjs/sitemap 5.2.0
@pinia/nuxt 0.5.1
js-yaml 4.1.0
pinia 2.1.7
sitemap 8.0.0
vue-leaflet 0.1.0

devDependencies:
@nuxt/devtools 1.3.3
@nuxtjs/device 3.1.1
@nuxtjs/google-fonts 3.1.3
@nuxtjs/tailwindcss 6.11.4
nuxt 3.12.1
nuxt3-leaflet 1.0.13
vue 3.4.18
vue-router 4.2.5
```

Console Errors: ![error](https://github.com/Gugustinette/Nuxt-Leaflet/assets/7724420/d2194daf-17ec-421e-a5e5-814d66d89ff8)

If you need more information, please let me know. Any help would be greatly appreciated!

Kind regards,
Marcel Riedeman

**Comment by Gugustinette** [comment]
Hi !

As featured [here](https://gugustinette.github.io/Nuxt-Leaflet/getting-started/usage.html) in the documentation, you now need to add `:use-global-leaflet="false"` to your LMap if you want to let the library import Leaflet automatically.

```vue
<template>
  <LMap
    style="height: 350px"
    :zoom="6"
    :center="[47.21322, -1.559482]"
    :use-global-leaflet="false"
  >
    <LTileLayer
      url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      attribution="&amp;copy; <a href=&quot;https://www.openstreetmap.org/&quot;>OpenStreetMap</a> contributors"
      layer-type="base"
      name="OpenStreetMap"
    />
  </LMap>
</template>
```

We had to change this behavior, to make sure Leaflet is not imported everywhere in your app, even when there's no map.

**Comment by MarcelRiedeman** [comment]
Thanks! This fixed the issue for me!

**Comment by nossienl** [comment]
still not working , tried everything still getting the same error
