### ISSUE TITLE
Access leaflet API

### ISSUE THREAD

**Issue by aprows-mobilityre** [Gugustinette/Nuxt-Leaflet#6]
I'm trying to do this: [https://vue2-leaflet.netlify.app/quickstart/#accessing-leaflet-api ](https://vue2-leaflet.netlify.app/quickstart/#accessing-leaflet-api) but as far as I can tell, the ref for the `<LMap>` component doesn't have the `mapObject` or equivalent. How do I call the leaflet methods?

Edit: I found it, the property is called `leafletObject` see: [https://github.com/vue-leaflet/vue-leaflet/blob/master/docs/faq/index.md#how-can-i-access-the-leaflet-map-object](https://github.com/vue-leaflet/vue-leaflet/blob/master/docs/faq/index.md#how-can-i-access-the-leaflet-map-object)

**Comment by Gugustinette** [comment]
Yeah some things like this could be better documented in a "Nuxt Leaflet Doc", I should write that to have a clean and modern doc of the libray, components, common usages,....

Thanks for reaching out anyway ! This will be useful for future documentation.
