### ISSUE TITLE
I got this error when i use nuxt3-leaflet: Uncaught ReferenceError: __NUXT_ASYNC_CONTEXT__ is not defined

### ISSUE THREAD

**Issue by m-sam-mohamadi** [Gugustinette/Nuxt-Leaflet#7]
Hi
i install every version of nuxt3-leaflet but i got this error:
Uncaught ReferenceError: __NUXT_ASYNC_CONTEXT__ is not defined

i followed the documentation but nothing happened

my nuxt version: 3.9
and i use debian 12

**Comment by Gugustinette** [comment]
Hi,

Can you provide more context ?
Like is the plugin loading on a server or a client component/page ?
