### ISSUE TITLE
Thank you 🙏🏻

### ISSUE THREAD

**Issue by PatrikBird** [Gugustinette/Nuxt-Leaflet#8]
just wanted to tell you that this module works like a charm 💚 thanks a bunch!

**Comment by Gugustinette** [comment]
Ahah thanks !

<img src="https://i.kym-cdn.com/entries/icons/original/000/028/021/work.jpg" width="400px" />

_I still have things to improve_ but I'm happy that it helps people using maps on their application (which shouldn't be THIS hard without a Nuxt Module...)
